### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by isaklafleur** [regexhq/word-regex#5]
Hello!

Great package!

Is it difficult to add for example the following features in a config object
- min char for a word, ex minChar: 2 -> "ha" is not valid, but "haa" is.
- Allow extra special characters inside a word. (maybe this one is a bit to complicated) :)
ex. O-RING, and ORING are the same part. 

Thank you!
Isak

**Comment by tunnckoCore** [comment]
Hey! :wave: 

Good ideas, but probably using regex for this isn't the right way. And yes, allowing certain special characters may be a bit complicated, because this regex also works for non-latin alphabets, meaning it's not just `\w+` which in most cases may be enough.

You may create something on top of that regex to set your needs. And if you need some more optimizations you can try [regex-cache](https://github.com/jonschlinkert/regex-cache) too.

Sorry will close that :)
Good luck.
